//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhatThuong
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_QuanLyPhatThuongTDPEntities : DbContext
    {
        public db_QuanLyPhatThuongTDPEntities()
            : base("name=db_QuanLyPhatThuongTDPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_ChiTietPhanThuong> tb_ChiTietPhanThuong { get; set; }
        public virtual DbSet<tb_ChiTietPhatThuong> tb_ChiTietPhatThuong { get; set; }
        public virtual DbSet<tb_DanhSachPhatThuong> tb_DanhSachPhatThuong { get; set; }
        public virtual DbSet<tb_HoGiaDinh> tb_HoGiaDinh { get; set; }
        public virtual DbSet<tb_LoaiPhanThuong> tb_LoaiPhanThuong { get; set; }
        public virtual DbSet<tb_PhanThuong> tb_PhanThuong { get; set; }
        public virtual DbSet<tb_ThanhTichHocTap> tb_ThanhTichHocTap { get; set; }
        public virtual DbSet<tb_ThanhVienHoGiaDinh> tb_ThanhVienHoGiaDinh { get; set; }
    }
}
