//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhatThuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ChiTietPhanThuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_ChiTietPhanThuong()
        {
            this.tb_ChiTietPhatThuong = new HashSet<tb_ChiTietPhatThuong>();
        }
    
        public int ID { get; set; }
        public int ID_PhanThuong { get; set; }
        public string Ten { get; set; }
        public int SoLuong { get; set; }
        public Nullable<int> ChiPhi { get; set; }
        public string NhaCC { get; set; }
        public string DiaChiNCC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietPhatThuong> tb_ChiTietPhatThuong { get; set; }
        public virtual tb_PhanThuong tb_PhanThuong { get; set; }
    }
}
