//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhatThuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DanhSachPhatThuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_DanhSachPhatThuong()
        {
            this.tb_ChiTietPhatThuong = new HashSet<tb_ChiTietPhatThuong>();
        }
    
        public int ID { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public Nullable<double> TongChiPhi { get; set; }
        public Nullable<System.DateTime> NgayTaoDanhSach { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietPhatThuong> tb_ChiTietPhatThuong { get; set; }
    }
}
