//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhatThuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_HoGiaDinh
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_HoGiaDinh()
        {
            this.tb_ThanhVienHoGiaDinh = new HashSet<tb_ThanhVienHoGiaDinh>();
        }
    
        public int ID { get; set; }
        public string MaHoGiaDinh { get; set; }
        public int SoThanhVien { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ThanhVienHoGiaDinh> tb_ThanhVienHoGiaDinh { get; set; }
    }
}
