//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhatThuong
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_PhanThuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_PhanThuong()
        {
            this.tb_ChiTietPhanThuong = new HashSet<tb_ChiTietPhanThuong>();
        }
    
        public int ID { get; set; }
        public int ID_LoaiPhanThuong { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> TriGia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ChiTietPhanThuong> tb_ChiTietPhanThuong { get; set; }
        public virtual tb_LoaiPhanThuong tb_LoaiPhanThuong { get; set; }
    }
}
