//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhatThuong_ToDanPho_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_QuanLyPhatThuong_ToDanPhoEntities : DbContext
    {
        public db_QuanLyPhatThuong_ToDanPhoEntities()
            : base("name=db_QuanLyPhatThuong_ToDanPhoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_ChiTietPhatThuong> tb_ChiTietPhatThuong { get; set; }
        public virtual DbSet<tb_DanhMucPhatThuong> tb_DanhMucPhatThuong { get; set; }
        public virtual DbSet<tb_HoGiaDinh> tb_HoGiaDinh { get; set; }
        public virtual DbSet<tb_LoaiPhanThuong> tb_LoaiPhanThuong { get; set; }
        public virtual DbSet<tb_PhanThuong> tb_PhanThuong { get; set; }
        public virtual DbSet<tb_PhatThuong> tb_PhatThuong { get; set; }
        public virtual DbSet<tb_ThanhTichHocTap> tb_ThanhTichHocTap { get; set; }
        public virtual DbSet<tb_ThanhVien> tb_ThanhVien { get; set; }
        public virtual DbSet<tb_Log> tb_Log { get; set; }
        public virtual DbSet<tb_TaiKhoan> tb_TaiKhoan { get; set; }
    }
}
