//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhatThuong_ToDanPho_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_ChiTietPhatThuong
    {
        public int ID { get; set; }
        public int ID_PhatThuong { get; set; }
        public int ID_ThanhVien { get; set; }
        public int ID_PhanThuong { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> TriGia { get; set; }
        public Nullable<int> TongTien { get; set; }
        public string GhiChu { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual tb_PhatThuong tb_PhatThuong { get; set; }
        public virtual tb_PhanThuong tb_PhanThuong { get; set; }
        public virtual tb_ThanhVien tb_ThanhVien { get; set; }
    }
}
