//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhatThuong_ToDanPho_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_DanhMucPhatThuong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_DanhMucPhatThuong()
        {
            this.tb_PhatThuong = new HashSet<tb_PhatThuong>();
        }
    
        public int ID { get; set; }
        public string TenDanhMuc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_PhatThuong> tb_PhatThuong { get; set; }
    }
}
