//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyPhatThuong_ToDanPho_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Log
    {
        public int ID { get; set; }
        public int ID_TaiKhoan { get; set; }
        public Nullable<System.DateTime> NgayThaoTac { get; set; }
        public string NoiDung { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual tb_TaiKhoan tb_TaiKhoan { get; set; }
    }
}
